services:
  ros2:
    build: .
    container_name: ros2_container
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    command: >
      /bin/bash -c "
        source /opt/ros/kilted/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        ros2 run charged_creeper communication_node
      "
